POST http://localhost:3003/api/blogs/6139e47d18bdd81d6c93f12a/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxvb24iLCJpZCI6IjYxMzllYzc5NWIzYWI2MjhlMGFmZDFkOSIsImlhdCI6MTYzNDE0NDU4NX0.ZBpyS-K5gPLtq2vri6I7rTe0NDslBjPRlYBzUZB8kp8

{
    "comment": "Test something"
}