POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCIpXVCJ9.eyJ1c2VybmFtZSI6Imxvb24iLCJpZCI6IjYxMzllYzc5NWIzYWI2MjhlMGFmZDFkOSIsImlhdCI6MTYzMTE4NjA2MX0.77I8SLURPhF2e5dtITyLVoCvxdDJcHlPaGnMISerKEY

{
  "title": "How to create blogs",
  "author": "Loon",
  "url": "http://asdagadsfg.com",
  "likes": 94
}